param(
    [string]$AuditPath = (Join-Path (Get-Location) 'PHASE5_8_VECTOR_PROVENANCE_AUDIT.json'),
    [string]$RegressionPath = (Join-Path (Get-Location) 'PHASE5_8_RETRIEVAL_REGRESSION.json')
)
$ErrorActionPreference='Stop'
$goldNode=ConvertFrom-Json -InputObject (Get-Content -Raw 'rag/src/main/resources/evaluation/phase2b_gold.json');$gold=foreach($x in $goldNode){$x}
$currentSql="SELECT d.id||E'\t'||d.doc_name||E'\t'||d.quality_status||E'\t'||count(v.id) FROM t_knowledge_document d JOIN t_knowledge_chunk c ON c.doc_id=d.id AND c.index_eligible=TRUE AND c.deleted=0 LEFT JOIN t_knowledge_vector v ON v.id=c.id AND v.collection_name='legal_corpus_2b' WHERE d.kb_id='legal-corpus-2b' AND d.file_type='pdf' AND d.parser_version='legal-pdf-mineru-adapter/2.0.0' AND d.deleted=0 GROUP BY d.id,d.doc_name,d.quality_status ORDER BY d.doc_name;"
$current=@(docker exec ragent-postgres psql -U postgres -d ragent -A -t -F "`t" -P footer=off -c $currentSql|ForEach-Object{$p=$_ -split "`t",4;if($p.Count -eq 4){[pscustomobject]@{id=$p[0];name=$p[1];status=$p[2];vectors=[int]$p[3]}}})
$allCount=[int](docker exec ragent-postgres psql -U postgres -d ragent -At -c "SELECT count(*) FROM t_knowledge_vector WHERE collection_name='legal_corpus_2b';")
$oldPdf=[int](docker exec ragent-postgres psql -U postgres -d ragent -At -c "SELECT count(*) FROM t_knowledge_vector v JOIN t_knowledge_document d ON d.id=v.metadata->>'doc_id' WHERE v.collection_name='legal_corpus_2b' AND d.file_type='pdf' AND d.parser_version<>'legal-pdf-mineru-adapter/2.0.0';")
$currentCount=($current|Measure-Object vectors -Sum).Sum
$padBody=(@{model='bge-m3';input=@('Phase 5.8 deterministic embedding probe')}|ConvertTo-Json -Compress);$pad1=Invoke-RestMethod -Uri 'http://127.0.0.1:18083/v1/embeddings' -Method Post -ContentType 'application/json' -Body $padBody -TimeoutSec 30;$pad2=Invoke-RestMethod -Uri 'http://127.0.0.1:18083/v1/embeddings' -Method Post -ContentType 'application/json' -Body $padBody -TimeoutSec 30;$native1=@($pad1.data[0].embedding);$native2=@($pad2.data[0].embedding);$app1=@($native1);$app2=@($native2);while($app1.Count -lt 1536){$app1+=0};while($app2.Count -lt 1536){$app2+=0};$samePrefix=($native1.Count -eq $native2.Count -and -not (Compare-Object $native1 $native2));$zeroTail=(@($app1[1024..1535]|Where-Object {$_ -ne 0}).Count -eq 0)
$audit=[ordered]@{schemaVersion=1;phase='5.8';generatedAt=(Get-Date).ToUniversalTime().ToString('o');totalVectors=$allCount;historicalSourceVectors=31086;currentPdfSourceVectors=5256;historicalVectors=($allCount-$currentCount);currentBgeM3Vectors=$allCount;unknownVectors=31086;embeddingSpaces=@(@{name='final-unified';provider='tei';model='bge-m3';nativeDimension=1024;applicationDimension=1536;vectorCount=$allCount;transform='zero-pad native 1024 to application 1536';basis=@('post-Strategy-B full reindex log','all-eligible Legal Chunk scope')},@{name='historical-source-before-migration';provider='bailian';model='text-embedding-v4';nativeDimension=1536;applicationDimension=1536;vectorCount=31086;status='replaced';basis=@('PHASE2B historical report','bootstrap embedding configuration','historical indexing logs')});metadataFieldsPresent=@('doc_id','document_id','chunk_id via vector id','doc_title','standard_no','clause_no','chunk_index','collection_name');metadataFieldsMissing=@('embeddingProvider','embeddingModel','embeddingDimension','createdAt');historicalPdfVectors=$oldPdf;queryEmbeddingAudit=@{provider='tei';model='bge-m3';nativeDimension=1024;applicationDimension=1536;deterministicSamePrefix=$samePrefix;zeroPaddedTail512=$zeroTail;queryText='Phase 5.8 deterministic embedding probe'};currentDocuments=@($current|Select-Object id,name,status,vectors)}
$audit|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $AuditPath -Encoding UTF8
$available=@(docker exec ragent-postgres psql -U postgres -d ragent -A -t -P footer=off -c "SELECT DISTINCT d.doc_name FROM t_knowledge_vector v JOIN t_knowledge_document d ON d.id=v.metadata->>'doc_id' WHERE v.collection_name='legal_corpus_2b';")
$currentDocs=@($current);$allRows=@()
foreach($g in $gold){
  $body=(@{model='bge-m3';input=@($g.query)}|ConvertTo-Json -Compress);$x=Invoke-RestMethod -Uri 'http://127.0.0.1:18083/v1/embeddings' -Method Post -ContentType 'application/json' -Body $body -TimeoutSec 30;$a=@($x.data[0].embedding);while($a.Count -lt 1536){$a+=0};$v='['+($a -join ',')+']'
  $q="SELECT d.doc_name,d.quality_status FROM t_knowledge_vector v JOIN t_knowledge_document d ON d.id=v.metadata->>'doc_id' JOIN t_knowledge_chunk c ON c.id=v.id WHERE v.collection_name='legal_corpus_2b' AND d.parser_version='legal-pdf-mineru-adapter/2.0.0' AND d.file_type='pdf' AND c.index_eligible=TRUE ORDER BY v.embedding <=> '$v'::vector LIMIT 20;"
  $qa="SELECT d.doc_name,d.quality_status FROM t_knowledge_vector v JOIN t_knowledge_document d ON d.id=v.metadata->>'doc_id' WHERE v.collection_name='legal_corpus_2b' ORDER BY v.embedding <=> '$v'::vector LIMIT 20;"
  $topA=@(docker exec ragent-postgres psql -U postgres -d ragent -A -t -F "`t" -P footer=off -c $q|ForEach-Object{$p=$_ -split "`t",2;if($p.Count -eq 2){[pscustomobject]@{name=$p[0];status=$p[1]}}});$topB=@(docker exec ragent-postgres psql -U postgres -d ragent -A -t -F "`t" -P footer=off -c $qa|ForEach-Object{$p=$_ -split "`t",2;if($p.Count -eq 2){[pscustomobject]@{name=$p[0];status=$p[1]}}})
  function Rank($top,$docs){for($i=0;$i -lt $top.Count;$i++){foreach($doc in @($docs)){if($top[$i].name -like "*$doc*"){return $i+1}}};return 0}
  $rankA=Rank $topA $g.gold_documents;$rankB=Rank $topB $g.gold_documents;$source='historicalNonPdf';$sourceStatus='NONE';foreach($doc in @($g.gold_documents)){ $m=$currentDocs|Where-Object{$_.name -like "*$doc*"};if($m){$source='currentPdf';$sourceStatus=(@($m|Select-Object -ExpandProperty status) -join ',');break};if($available|Where-Object{$_ -like "*$doc*"}){$source='historicalIndexed';$sourceStatus='INDEXED';break}}
  $allRows += [pscustomobject]@{query=$g.query;goldDocuments=@($g.gold_documents);sourceClass=$source;sourceStatus=$sourceStatus;rankCurrentPdf=$rankA;rankFullCollection=$rankB;topCurrentPdf=@($topA|Select-Object -ExpandProperty name);topFullCollection=@($topB|Select-Object -ExpandProperty name)}
}
function Metric($rs,$k){$n=@($rs).Count;if(!$n){return 0};return [math]::Round((@($rs|Where-Object{$_.rankCurrentPdf -gt 0 -and $_.rankCurrentPdf -le $k}).Count/[double]$n),4)}
function MetricFull($rs,$k){$n=@($rs).Count;if(!$n){return 0};return [math]::Round((@($rs|Where-Object{$_.rankFullCollection -gt 0 -and $_.rankFullCollection -le $k}).Count/[double]$n),4)}
function Mrr($rs,$k,$field){$n=@($rs).Count;if(!$n){return 0};$s=0.0;foreach($r in $rs){$rank=$r.$field;if($rank -gt 0 -and $rank -le $k){$s+=1.0/$rank}};return [math]::Round($s/$n,4)}
function Ndcg($rs,$k,$field){$n=@($rs).Count;if(!$n){return 0};$s=0.0;foreach($r in $rs){$rank=$r.$field;if($rank -gt 0 -and $rank -le $k){$s+=1.0/[math]::Log($rank+1,2)}};return [math]::Round($s/$n,4)}
$cp=@($allRows|Where-Object sourceClass -eq 'currentPdf');$iso=@($cp|Where-Object sourceStatus -like 'REVIEW*');$hist=@($allRows|Where-Object sourceClass -ne 'currentPdf');$full=@($allRows)
$reg=[ordered]@{schemaVersion=1;phase='5.8';totalOriginalGold=$full.Count;currentPdfGold=$cp.Count;isolatedPdfGold=$iso.Count;historicalNonPdfGold=$hist.Count;currentPdfMetrics=@{RecallAt1=(Metric $cp 1);RecallAt3=(Metric $cp 3);RecallAt5=(Metric $cp 5);RecallAt10=(Metric $cp 10);RecallAt20=(Metric $cp 20);MRR10=(Mrr $cp 10 'rankCurrentPdf');MRR20=(Mrr $cp 20 'rankCurrentPdf');nDCG10=(Ndcg $cp 10 'rankCurrentPdf');MissAt20=(@($cp|Where-Object{$_.rankCurrentPdf -eq 0}).Count)};fullCollectionMetrics=@{RecallAt1=(MetricFull $full 1);RecallAt3=(MetricFull $full 3);RecallAt5=(MetricFull $full 5);RecallAt10=(MetricFull $full 10);RecallAt20=(MetricFull $full 20);MRR10=(Mrr $full 10 'rankFullCollection');MRR20=(Mrr $full 20 'rankFullCollection');nDCG10=(Ndcg $full 10 'rankFullCollection');MissAt20=(@($full|Where-Object{$_.rankFullCollection -eq 0}).Count)};cases=$allRows;note='Query vectors were generated by the existing TEI bge-m3 endpoint and padded to 1536 by the existing application transform. Current-only and full-collection Top20 are reported separately.'}
$reg|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $RegressionPath -Encoding UTF8
Write-Host "Audit vectors=$allCount current=$currentCount historical=$($allCount-$currentCount); Gold total=$($full.Count) currentPdf=$($cp.Count) isolated=$($iso.Count); currentRecall20=$(Metric $cp 20) fullRecall20=$(MetricFull $full 20)"
