param([switch]$SkipFrontend,[switch]$SkipBackend,[switch]$StartRocketMq)
$ErrorActionPreference='Stop';$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$runDir=Join-Path $repoRoot '.codex-run';New-Item -ItemType Directory -Force $runDir|Out-Null
function S([string]$l,[string]$m){Write-Host "[$l] $m"};function W([int]$p,[string]$n){for($i=0;$i-lt 60;$i++){if((Test-NetConnection 127.0.0.1 -Port $p -WarningAction SilentlyContinue).TcpTestSucceeded){S OK "$n reachable on $p";return};Start-Sleep 1};throw "$n did not start on port $p. Check .codex-run logs."}
if(-not(Get-Command docker -ErrorAction SilentlyContinue)){throw 'Docker CLI not found.'};docker info *> $null;if($LASTEXITCODE-ne 0){throw 'Docker Desktop is not running.'};S OK 'Docker Desktop is ready'
& (Join-Path $repoRoot 'scripts\windows\start-ragent-required-middleware.ps1');W 15432 PostgreSQL;W 9000 'RustFS API'
if((Test-NetConnection 127.0.0.1 -Port 6379 -WarningAction SilentlyContinue).TcpTestSucceeded){$old=docker ps --filter 'name=^/ragent-redis-phase1$' --format '{{.Names}}';if($old-eq 'ragent-redis-phase1'){docker stop ragent-redis-phase1|Out-Null;S OK 'Stopped legacy no-password ragent-redis-phase1 (volume preserved)'}}
$redisCompose=Join-Path $repoRoot 'resources\docker\redis-local.compose.yaml';docker compose -f $redisCompose up -d;if($LASTEXITCODE-ne 0){throw 'Redis startup failed. Port 6379 may be used by another service.'};W 6379 Redis
if($StartRocketMq){$f=Join-Path $repoRoot 'resources\docker\rocketmq-stack-5.2.0.compose.yaml';docker compose -f $f up -d;if($LASTEXITCODE-ne 0){throw 'RocketMQ startup failed.'};W 9876 'RocketMQ NameServer'}else{S WARN 'RocketMQ not started; use -StartRocketMq if required'}
if(Get-NetTCPConnection -LocalPort 11434 -State Listen -ErrorAction SilentlyContinue){S OK 'Ollama available on 11434'}else{S WARN 'Ollama unavailable (optional dependency)'}
if(-not $SkipBackend){if(-not(Get-NetTCPConnection -LocalPort 9090 -State Listen -ErrorAction SilentlyContinue)){Start-Process cmd.exe -ArgumentList @('/c','.\mvnw.cmd -pl bootstrap -am package "-DskipTests" "-Dspotless.check.skip=true" && java -jar bootstrap\target\bootstrap-0.0.1-SNAPSHOT.jar') -WorkingDirectory $repoRoot -RedirectStandardOutput (Join-Path $runDir 'ragent-backend.out.log') -RedirectStandardError (Join-Path $runDir 'ragent-backend.err.log') -WindowStyle Hidden|Out-Null;W 9090 'ragent backend'}else{S OK 'ragent backend already listens on 9090'}}
if(-not $SkipFrontend){if(-not(Get-NetTCPConnection -LocalPort 5173 -State Listen -ErrorAction SilentlyContinue)){Start-Process npm.cmd -ArgumentList @('--prefix','frontend','run','dev') -WorkingDirectory $repoRoot -RedirectStandardOutput (Join-Path $runDir 'ragent-frontend.out.log') -RedirectStandardError (Join-Path $runDir 'ragent-frontend.err.log') -WindowStyle Hidden|Out-Null;W 5173 'ragent frontend'}else{S OK 'ragent frontend already listens on 5173'}}
Write-Host '';Write-Host 'Frontend URL: http://127.0.0.1:5173';Write-Host 'Backend URL: http://127.0.0.1:9090/api/ragent'
